<?php

namespace Jh\Bundle\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository {

    public function findOneById($id) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT j, ca, co FROM JhJobBundle:Job j
            JOIN j.category ca
            JOIN j.contract co
            WHERE j.id = :id')->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findAllJobs() {
        $query = $this->getEntityManager()
                ->createQuery("
                    SELECT j, c, co
                    FROM JhJobBundle:Job j 
                    JOIN j.category c
                    JOIN j.contract co");
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}