<?php

namespace Jh\Bundle\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends EntityRepository
{
}