<?php

namespace Jh\Bundle\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuburbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuburbRepository extends EntityRepository
{
    public function findOneById($id) {
        $query = $this->getEntityManager()
                        ->createQuery("
            SELECT CONCAT(CONCAT(s.name, r.name), p.name) as name 
            FROM JhJobBundle:Suburb s
            JOIN s.region r
            JOIN r.province p
            WHERE s.id = :id")->setParameter('id', $id);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}